server:
  port: 8087

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.openorderflow: DEBUG

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
