package com.openorderflow.order.entity;


public enum OrderStatusEnum {
    CREATION_REQUESTED,
    INVENTORY_VALIDATED,
    INVENTORY_REJECTED,
    BUSINESS_ACCEPTED,
    BUSINESS_REJECTED,
    BUSINESS_PREPARATION_STARTED,
    DELIVERY_ASSIGNMENT_STARTED,
    DELIVERY_PARTNER_ASSIGNED,
    BUSINESS_PREPARED,
    DELIVERY_PARTNER_PICKED_UP,
    DELIVERED,
    RATED,
    UNKNOWN_STATE
}