services:
  postgres-db:
    image: postgres:17
    container_name: openorderflowdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: openorderflowdb
    ports:
      - "5432:5432"
    volumes:
      - user_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: openorderflow-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@openorderflow.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres-db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  user_data:
  pgadmin_data:
